Controllers/OrdersController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewStudio.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;

namespace NewStudio.Views
{
    public class OrdersController : Controller
    {
        private readonly context _context;

        public OrdersController(context context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var context = _context.orders.Include(o => o.User).Include(o => o.Tovar);
            return View(await context.ToListAsync());
        }

        public async Task<IActionResult> Oplata(int id)
        {
            IQueryable<Order> orders = _context.orders;
            orders = orders.Where(x => x.User._Username == User.Identity.Name);
            orders = orders.Where(x => x.status == status.Open);
            foreach (Order order in orders)
            {
                order.status = status.Close;
                if (id == 1)
                {
                    order.type = global::type.Cash;
                }
                else
                {
                    order.type = global::type.Card;
                }
                _context.Update(order);
            }
            _context.SaveChanges();
            return RedirectToAction("Cart");
        }
        
        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.orders
                .Include(o => o.User)
                .Include(o => o.Tovar)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["TovarId"] = new SelectList(_context.Tovars, "Id", "Id");
            return View();
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,_Count,type,status,TovarId,UserId")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            ViewData["TovarId"] = new SelectList(_context.Tovars, "Id", "Id", order.TovarId);
            return View(order);
        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            ViewData["TovarId"] = new SelectList(_context.Tovars, "Id", "Id", order.TovarId);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,_Count,type,status,TovarId,UserId")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", order.UserId);
            ViewData["TovarId"] = new SelectList(_context.Tovars, "Id", "Id", order.TovarId);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.orders
                .Include(o => o.User)
                .Include(o => o.Tovar)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var order = await _context.orders.FindAsync(id);
            _context.orders.Remove(order);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderExists(int id)
        {
            return _context.orders.Any(e => e.Id == id);
        }
        public async Task<IActionResult> Cart()
        {
            User currentUser = await _context.Users.FirstOrDefaultAsync(x => x._Username == User.Identity.Name);
            IQueryable<Order> orders = _context.orders
                .Include(x => x.Tovar)
                .Include(x => x.User).Where(x => x.UserId == currentUser.Id);
            orders = orders.Where(x => x.status == status.Open);
            return View(orders);
        }
        [Authorize]
        public async Task<IActionResult> addToCart(int? id)
        {
            User currentUser = await _context.Users.FirstOrDefaultAsync(x => x._Username == User.Identity.Name);
            foreach (Order orders in _context.orders)
            {
                if (orders.UserId == currentUser.Id && orders.TovarId == id && orders.status == status.Open)
                {
                    orders._Count++;
                    id = null;
                    _context.orders.Update(orders);
                }

            }
            if (id != null)
            {
                Order order = new Order { TovarId = (int)id, UserId = currentUser.Id, _Count = 1, type = type.Card, status = status.Open };
                _context.orders.Add(order);
            }
            _context.SaveChanges();
            return RedirectToAction("Index","Home");
        }
    }
}

Controllers/TovarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NewStudio.Models;

namespace NewStudio.Controllers
{
    public class TovarController : Controller
    {
        private readonly context _context;

        public TovarController(context context)
        {
            _context = context;
        }

        // GET: Tovars
        public async Task<IActionResult> AdminPanel()
        {
            return View();
        }
        public async Task<IActionResult> Index(int? id)
        {
            //Фильтрация
            IQueryable<Tovar> Tovar = _context.Tovars;
            if(id == 0)
            {
                return View(Tovar);
            }
            else
            {
                Tovar = Tovar.Where(x => x.category == (category)id);
                return View(Tovar);
            }
        }
        // GET: Tovars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Tovar = await _context.Tovars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Tovar == null)
            {
                return NotFound();
            }
            return View(Tovar);
        }

        // GET: Tovars/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Tovars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cost,Name,Image,category,Description")] Tovar Tovar)
        {
            if (ModelState.IsValid)
            {
                _context.Add(Tovar);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home");
            }
            return View(Tovar);
        }

        // GET: Tovars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Tovar = await _context.Tovars.FindAsync(id);
            if (Tovar == null)
            {
                return NotFound();
            }
            return View(Tovar);
        }

        // POST: Tovars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Cost,Name,Image,category,Description")] Tovar Tovar)
        {
            if (id != Tovar.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(Tovar);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TovarExists(Tovar.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return View(Tovar);
        }
        public async Task<IActionResult> Search(int? stuffs, string name)
        {
            //Фильтрация
            IQueryable<Tovar> tovar = _context.Tovars;
            if (!String.IsNullOrEmpty(name))
            {
                tovar = tovar.Where(x => x.Name.Contains(name));
            }
            svm svm = new svm
            {
                Tovars = tovar,
                viewModel = new searchViewModel(_context.Tovars.ToList(), stuffs, name)
            };
            return View(svm);

        }
        // GET: Tovars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
                
            var Tovar = await _context.Tovars
                .FirstOrDefaultAsync(m => m.Id == id);
            if (Tovar == null)
            {
                return NotFound();
            }

            return View(Tovar);
        }

        // POST: Tovars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Tovar = await _context.Tovars.FindAsync(id);
            _context.Tovars.Remove(Tovar);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        private bool TovarExists(int id)
        {
            return _context.Tovars.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NewStudio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Магазин</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1 justify-content-end">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Search" asp-controller="Tovar">Поиск</a>
                        </li>
                        @if (User.IsInRole("admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Tovar" asp-action="AdminPanel">Управление</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            @if (User.IsInRole("user"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-controller="Orders" asp-action="Cart">Корзина</a>
                                </li>
                            }
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Details" asp-route-id="@User.Identity.Name">@User.Identity.Name</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Users" asp-action="Logout">Выход</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Login" asp-controller="Users">Войти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-action="Register" asp-controller="Users">Регистрация</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NewStudio - ул. Немига 12, Минск
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>